# Generated by Django 3.1.1 on 2020-09-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200906_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='age_limit',
            field=models.IntegerField(blank=True, choices=[(7, 'little kid'), (13, 'teen'), (18, 'EU adult'), (21, 'US adult'), (36, 'senator')], null=True),
        ),
    ]
