# Generated by Django 3.1.1 on 2020-09-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200906_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.TextField(default='USA', max_length=30, unique=True),
        ),
    ]
