# Generated by Django 3.1.1 on 2020-09-11 14:38

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200906_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('country', models.ForeignKey(default=core.models.Country, on_delete=django.db.models.deletion.CASCADE, to='core.country')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='boxoffices',
            field=models.ManyToManyField(related_name='movies', to='core.BoxOffice'),
        ),
    ]
