# Generated by Django 3.1.1 on 2020-09-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200911_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='boxoffices',
            field=models.ManyToManyField(blank=True, null=True, related_name='movies', to='core.BoxOffice'),
        ),
    ]
