# Generated by Django 3.1.1 on 2020-09-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200911_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='boxoffices',
            field=models.ManyToManyField(blank=True, related_name='movies', to='core.BoxOffice'),
        ),
    ]
